# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 688dab7f6ade77bf8c36699a86e3ac43248172e1baac7215916aa88aa71c385267a967f9382d5e17dd9504ef13165925d77b36171bd85f0bec36338901b7c8d4

test:
  secret_key_base: 1fb537ae071c33884dd5096c135fd3d4a15aeb5a86024790ac628778b84a57122a66bfc87b45bb04337462392f8917ce6407bafccf4d5b26de11091efdfc40d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
